# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: true
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

        # Solution 1: On laisse Debian gérer ça :
        # 0. Paramétrer le 'session.gc_maxlifetime' dans le php.ini <== !!!!!!!
        # 1. on ne change pas le save_path
        # save_path: ~
        # 2. on ne change pas le gc_probability
        # gc_probability: null

        # Solution 2: On gère ça nous-même :
        # 0. Symfony override le gc_maxlifetime
        # 1. sessions en local
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        # 2. TODO: vérifier que ça fonctionne

    #esi: true
    #fragments: true
    php_errors:
        log: true
