# https://github.com/dustin10/VichUploaderBundle/blob/master/docs/usage.md
vich_uploader:
    db_driver: orm

    mappings:
        medias:
            uri_prefix: /medias
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
