# https://github.com/dustin10/VichUploaderBundle/blob/master/docs/usage.md
vich_uploader:
    db_driver: orm
    storage: flysystem

    # https://github.com/dustin10/VichUploaderBundle/blob/master/docs/storage/flysystem.md#issues-with-adapters-public-url
    use_flysystem_to_resolve_uri: true

    mappings:
        documents:

            # flysystem
            upload_destination: uploads.storage

            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
